/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Example } from "./Example";
import { ExampleCountArgs } from "./ExampleCountArgs";
import { ExampleFindManyArgs } from "./ExampleFindManyArgs";
import { ExampleFindUniqueArgs } from "./ExampleFindUniqueArgs";
import { DeleteExampleArgs } from "./DeleteExampleArgs";
import { ExampleService } from "../example.service";
@graphql.Resolver(() => Example)
export class ExampleResolverBase {
  constructor(protected readonly service: ExampleService) {}

  async _examplesMeta(
    @graphql.Args() args: ExampleCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Example])
  async examples(
    @graphql.Args() args: ExampleFindManyArgs
  ): Promise<Example[]> {
    return this.service.examples(args);
  }

  @graphql.Query(() => Example, { nullable: true })
  async example(
    @graphql.Args() args: ExampleFindUniqueArgs
  ): Promise<Example | null> {
    const result = await this.service.example(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Example)
  async deleteExample(
    @graphql.Args() args: DeleteExampleArgs
  ): Promise<Example | null> {
    try {
      return await this.service.deleteExample(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
